print ('naaminvoer')
name = input ('Geef jouw naam: ')
print ('Hallo' +   name)
print ('Jouw adres')
name = input ('Geef jouw adres')
print ('Jouw adres is' +  name)
print ('Jouw postcode')
name = input ('Geef jouw postcode')
print ('jouw postcode is' + name)
print ('jouw Woonplaats')
name = input ('Geef jou woonplaats')
print ('jouw woonplaats is' + name)
print ('-------------------------------------')
name = 
